# -*- coding: utf-8 -*-
"""dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o-Kiaske-yUg83f2Linf8-39BX-EaRoy
"""

# ===========================================
# AI-POWERED DATA CENTER ENERGY DASHBOARD
# ===========================================

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor

# ----------------------------
# STEP 1: Create realistic synthetic dataset
# ----------------------------
np.random.seed(42)
n = 500

# Time column (hourly)
time = pd.date_range(start="2023-01-01", periods=n, freq="h")

# Server load (higher during working hours)
server_load = np.clip(
    np.random.normal(65, 15, n) + 10 * np.sin(2 * np.pi * time.hour / 24),
    30, 100
)

# Ambient temperature (slightly higher during day)
ambient_temp = np.clip(
    np.random.normal(24, 3, n) + 3 * np.sin(2 * np.pi * (time.hour - 6) / 24),
    18, 35
)

# Cooling efficiency (decreases as temp & load increase)
cooling_eff = np.clip(
    95 - 0.2 * ambient_temp - 0.1 * server_load + np.random.normal(0, 2, n),
    65, 95
)

# Hidden inefficiency factor (not used as feature)
inefficiency = np.random.uniform(0.85, 1.15, n)

# Nonlinear interaction
interaction = 0.03 * server_load * ambient_temp

# Energy consumption target
energy = (
    1.6 * server_load
    + 2.4 * ambient_temp
    - 1.2 * cooling_eff
    + interaction
) * inefficiency + np.random.normal(0, 20, n)

# Build dataframe
df = pd.DataFrame({
    "Time": time,
    "Server_Load_percent": server_load,
    "Ambient_Temperature_C": ambient_temp,
    "Cooling_Efficiency_percent": cooling_eff,
    "Energy_Consumption_kWh": energy
})

# ----------------------------
# STEP 2: Train ML model (XGBoost)
# ----------------------------
X = df[["Server_Load_percent", "Ambient_Temperature_C", "Cooling_Efficiency_percent"]]
y = df["Energy_Consumption_kWh"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = XGBRegressor(n_estimators=200, learning_rate=0.05, max_depth=4, random_state=42)
model.fit(X_train_scaled, y_train)

# ----------------------------
# STEP 3: Recommendation logic
# ----------------------------
def recommend_actions(server_load, temp, cooling_eff):
    features = np.array([[server_load, temp, cooling_eff]])
    features_scaled = scaler.transform(features)
    predicted_energy = model.predict(features_scaled)[0]

    actions = []
    threshold = 450  # Example threshold
    if predicted_energy > threshold:
        if server_load > 80:
            actions.append("Reduce server load (e.g., schedule non-critical tasks off-peak).")
        if cooling_eff < 75:
            actions.append("Increase cooling efficiency (adjust HVAC or airflow).")
    if not actions:
        actions.append("System operating efficiently. No action needed.")

    return predicted_energy, actions

# ----------------------------
# STEP 4: Streamlit Dashboard UI
# ----------------------------
st.title("Data Center Energy Dashboard")
st.markdown("### Real-time Energy Consumption Predictions & Recommendations")

# Interactive input sliders
server_input = st.slider("Server Load (%)", 30, 100, 65)
temp_input = st.slider("Ambient Temperature (°C)", 18, 35, 24)
cooling_input = st.slider("Cooling Efficiency (%)", 65, 95, 90)

pred_energy, action_list = recommend_actions(server_input, temp_input, cooling_input)

st.metric(label="Predicted Energy Consumption (kWh)", value=f"{pred_energy:.2f}")

st.markdown("### Recommended Actions:")
for action in action_list:
    st.write(f"- {action}")

# ----------------------------
# STEP 5: Visualizations
# ----------------------------
st.markdown("### Energy Consumption Over Time")
fig1 = px.line(df, x="Time", y="Energy_Consumption_kWh", title="Energy Consumption Over Time")
st.plotly_chart(fig1, use_container_width=True)

st.markdown("### Distribution of Server Load")
fig2 = px.histogram(df, x="Server_Load_percent", nbins=20, title="Server Load Distribution")
st.plotly_chart(fig2, use_container_width=True)

st.markdown("### Distribution of Ambient Temperature")
fig3 = px.histogram(df, x="Ambient_Temperature_C", nbins=20, title="Ambient Temperature Distribution")
st.plotly_chart(fig3, use_container_width=True)

st.markdown("### Distribution of Cooling Efficiency")
fig4 = px.histogram(df, x="Cooling_Efficiency_percent", nbins=20, title="Cooling Efficiency Distribution")
st.plotly_chart(fig4, use_container_width=True)